AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.10

  SAM template for Blender bpy in AWS Lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

# Parameters:
#   S3BucketName:
#     Type: String
#     Description: S3 Bucket Name

Resources:
  SimpleQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 900
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SimpleQueueDLQ.Arn
        maxReceiveCount: 5

  SimpleQueueDLQ:
    Type: AWS::SQS::Queue

  BpyLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Timeout: 900
      MemorySize: 1024
      EphemeralStorage:
        Size: 512
      # Policies:
      #   - S3CrudPolicy:
      #       BucketName: !Ref S3BucketName
      # Environment:
      #   Variables:
      #     S3_BUCKET: !Ref S3BucketName
      Events:
        BlenderLambdaFunctionEvent:
          Type: SQS # More info about SQS Event Source: https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md#sqs
          Properties:
            Queue: !GetAtt SimpleQueue.Arn
        # API GATEWAY - Uncomment if you want to use API GW as trigger
        # BpyLambdaApi:
        #   Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
        #   Properties:
        #     Path: /bpy
        #     Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./bpy_lambda

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # BpyLambdaApi:
  #   Description: "API Gateway endpoint URL for Prod stage for BpyLambda function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/bpy/"
  SimpleQueueArn:
    Description: "ARN for SimpleQueue"
    Value: !GetAtt SimpleQueue.Arn
  BpyLambdaFunction:
    Description: "BpyLambda Lambda Function ARN"
    Value: !GetAtt BpyLambdaFunction.Arn
  BpyLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for BpyLambda function"
    Value: !GetAtt BpyLambdaFunctionRole.Arn
